INSERT INTO profile (
    nickname,
    email,
    phone_number,
    profile_name,
    surname,
    patronymic,
    gender,
    birthday,
    bio,
    password_hash,
    password_salt
)
VALUES
    (
        'admin',
        'admin@example.com',
        '+79000000001',
        'Admin',
        'Adminov',
        'Adminovich',
        'male',
        '2000-01-01',
        'hi',
        'seed_hash_admin',
        'seed_salt_admin'
    );