// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "domain.AuthResponse": {
                "properties": {
                    "csrf_token": {
                        "example": "a1b2c3d4e5f6",
                        "type": "string"
                    },
                    "profile": {
                        "$ref": "#/components/schemas/domain.Profile"
                    }
                },
                "type": "object"
            },
            "domain.ErrorResponse": {
                "properties": {
                    "code": {
                        "example": "invalid_credentials",
                        "type": "string"
                    },
                    "message": {
                        "example": "Invalid credentials",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "domain.FeedResponse": {
                "properties": {
                    "has_more": {
                        "example": true,
                        "type": "boolean"
                    },
                    "limit": {
                        "example": 10,
                        "type": "integer"
                    },
                    "next_offset": {
                        "example": 20,
                        "type": "integer"
                    },
                    "offset": {
                        "example": 10,
                        "type": "integer"
                    },
                    "posts": {
                        "items": {
                            "$ref": "#/components/schemas/domain.Post"
                        },
                        "type": "array",
                        "uniqueItems": false
                    }
                },
                "type": "object"
            },
            "domain.Gender": {
                "enum": [
                    "male",
                    "female",
                    "other"
                ],
                "type": "string",
                "x-enum-varnames": [
                    "GenderMale",
                    "GenderFemale",
                    "GenderOther"
                ]
            },
            "domain.LoginRequest": {
                "properties": {
                    "login": {
                        "example": "ivan_petrov",
                        "maxLength": 254,
                        "type": "string"
                    },
                    "password": {
                        "example": "strongpassword123",
                        "maxLength": 64,
                        "minLength": 8,
                        "type": "string"
                    }
                },
                "required": [
                    "login",
                    "password"
                ],
                "type": "object"
            },
            "domain.MeResponse": {
                "properties": {
                    "csrf_token": {
                        "example": "a1b2c3d4e5f6",
                        "type": "string"
                    },
                    "profile": {
                        "$ref": "#/components/schemas/domain.Profile"
                    }
                },
                "type": "object"
            },
            "domain.Post": {
                "properties": {
                    "author": {
                        "$ref": "#/components/schemas/domain.Profile"
                    },
                    "author_community_id": {
                        "type": "integer"
                    },
                    "author_profile_id": {
                        "example": 1,
                        "type": "integer"
                    },
                    "comments_count": {
                        "example": 0,
                        "type": "integer"
                    },
                    "created_at": {
                        "example": "2026-01-01T12:00:00Z",
                        "type": "string"
                    },
                    "deleted_at": {
                        "type": "string"
                    },
                    "id": {
                        "example": 1,
                        "type": "integer"
                    },
                    "likes_count": {
                        "example": 0,
                        "type": "integer"
                    },
                    "media_count": {
                        "example": 1,
                        "type": "integer"
                    },
                    "media_urls": {
                        "items": {
                            "type": "string"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "post_text": {
                        "example": "Привет, мир!",
                        "type": "string"
                    },
                    "reposts_count": {
                        "example": 0,
                        "type": "integer"
                    },
                    "updated_at": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "domain.Profile": {
                "properties": {
                    "avatar_urls": {
                        "items": {
                            "type": "string"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "bio": {
                        "example": "hi!",
                        "type": "string"
                    },
                    "birthday": {
                        "example": "2000-05-14T00:00:00Z",
                        "type": "string"
                    },
                    "created_at": {
                        "example": "2026-01-01T12:00:00Z",
                        "type": "string"
                    },
                    "deleted_at": {
                        "type": "string"
                    },
                    "email": {
                        "example": "ivan@example.com",
                        "type": "string"
                    },
                    "gender": {
                        "$ref": "#/components/schemas/domain.Gender",
                        "example": "male"
                    },
                    "id": {
                        "example": 1,
                        "type": "integer"
                    },
                    "image_url": {
                        "example": "/api/media/avatar1.png",
                        "type": "string"
                    },
                    "nickname": {
                        "example": "ivan_petrov",
                        "type": "string"
                    },
                    "patronymic": {
                        "example": "Иванович",
                        "type": "string"
                    },
                    "phone_number": {
                        "example": "+79999999999",
                        "type": "string"
                    },
                    "profile_name": {
                        "example": "Иван",
                        "type": "string"
                    },
                    "surname": {
                        "example": "Иванов",
                        "type": "string"
                    },
                    "updated_at": {
                        "example": "2026-01-02T12:00:00Z",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "domain.RegisterRequest": {
                "properties": {
                    "bio": {
                        "example": "hi!",
                        "maxLength": 256,
                        "type": "string"
                    },
                    "birthday": {
                        "example": "2000-05-14",
                        "type": "string"
                    },
                    "confirm_password": {
                        "example": "sjkdfhgs4536njbjjkh",
                        "type": "string"
                    },
                    "email": {
                        "example": "ivan@example.com",
                        "maxLength": 254,
                        "type": "string"
                    },
                    "gender": {
                        "$ref": "#/components/schemas/domain.Gender",
                        "enum": [
                            "male",
                            "female"
                        ],
                        "example": "male"
                    },
                    "nickname": {
                        "example": "ivan67",
                        "maxLength": 32,
                        "minLength": 4,
                        "type": "string"
                    },
                    "password": {
                        "example": "sjkdfhgs4536njbjjkh",
                        "maxLength": 64,
                        "minLength": 8,
                        "type": "string"
                    },
                    "patronymic": {
                        "example": "Иванович",
                        "maxLength": 32,
                        "minLength": 2,
                        "type": "string"
                    },
                    "phone_number": {
                        "example": "+79999999999",
                        "type": "string"
                    },
                    "profile_name": {
                        "example": "Иван",
                        "maxLength": 32,
                        "minLength": 2,
                        "type": "string"
                    },
                    "surname": {
                        "example": "Иванов",
                        "maxLength": 32,
                        "minLength": 2,
                        "type": "string"
                    }
                },
                "required": [
                    "birthday",
                    "confirm_password",
                    "gender",
                    "nickname",
                    "password",
                    "profile_name",
                    "surname"
                ],
                "type": "object"
            }
        },
        "securitySchemes": {
            "SessionCookie": {
                "in": "cookie",
                "name": "session_id",
                "type": "apiKey"
            }
        }
    },
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "Авторизует пользователя и создаёт сессию",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/domain.LoginRequest",
                                "summary": "request",
                                "description": "Данные авторизации"
                            }
                        }
                    },
                    "description": "Данные авторизации",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/domain.AuthResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/domain.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/domain.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    }
                },
                "summary": "Авторизация пользователя",
                "tags": [
                    "auth"
                ]
            }
        },
        "/api/auth/logout": {
            "post": {
                "description": "Завершает текущую сессию пользователя.",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/domain.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "403": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/domain.ErrorResponse"
                                }
                            }
                        },
                        "description": "Forbidden"
                    }
                },
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "summary": "Выход из аккаунта",
                "tags": [
                    "auth"
                ]
            }
        },
        "/api/auth/me": {
            "get": {
                "description": "Возвращает пользователя по авторизованной сессии",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/domain.MeResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/domain.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "SessionCookie": []
                    }
                ],
                "summary": "Текущий пользователь",
                "tags": [
                    "auth"
                ]
            }
        },
        "/api/auth/register": {
            "post": {
                "description": "Регистрирует пользователя и создаёт авторизованную сессию",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/domain.RegisterRequest",
                                "summary": "request",
                                "description": "Данные регистрации"
                            }
                        }
                    },
                    "description": "Данные регистрации",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/domain.AuthResponse"
                                }
                            }
                        },
                        "description": "Created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/domain.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "409": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/domain.ErrorResponse"
                                }
                            }
                        },
                        "description": "Conflict"
                    }
                },
                "summary": "Регистрация пользователя",
                "tags": [
                    "auth"
                ]
            }
        },
        "/api/posts": {
            "get": {
                "description": "Возвращает посты в обратном хронологическом порядке",
                "parameters": [
                    {
                        "description": "Количество пропускаемых постов",
                        "in": "query",
                        "name": "offset",
                        "schema": {
                            "default": 0,
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Размер страницы (максимум 10)",
                        "in": "query",
                        "name": "limit",
                        "schema": {
                            "default": 10,
                            "maximum": 10,
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/domain.FeedResponse"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "Лента публикаций",
                "tags": [
                    "posts"
                ]
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "description": "Локальный backend",
            "url": "http://localhost:8080"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Title:            "Kvmm API",
	Description:      "API для регистрации, авторизации и последовательной ленты постов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
